language: node_js
node_js:
  - "node"
env:
  - EXTENSION_ID=ajmjbhndjfmegheielkjcmmgddkaghee
script:
  - echo "skipping tests"
deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
    tags: false
